global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:4000"]
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:4001"]
  - job_name: "shipment-service"
    static_configs:
      - targets: ["shipment-service:4002"]
  - job_name: "warehouse-service"
    static_configs:
      - targets: ["warehouse-service:4003"]
  - job_name: "courier-service"
    static_configs:
      - targets: ["courier-service:4004"]
  - job_name: "dispatch-service"
    static_configs:
      - targets: ["dispatch-service:4005"]
  - job_name: "tracking-service"
    static_configs:
      - targets: ["tracking-service:4006"]
  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:4007"]
  - job_name: "analytics-service"
    static_configs:
      - targets: ["analytics-service:4008"]
  - job_name: "ai-service"
    static_configs:
      - targets: ["ai-service:4009"]
